// Code generated by "stringer -type Hobby"; DO NOT EDIT.

package main

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Undefined-0]
	_ = x[Diving-1]
	_ = x[Motorcycles-2]
	_ = x[Espresso-3]
	_ = x[MountainBiking-4]
	_ = x[Skiing-5]
}

const _Hobby_name = "UndefinedDivingMotorcyclesEspressoMountainBikingSkiing"

var _Hobby_index = [...]uint8{0, 9, 15, 26, 34, 48, 54}

func (i Hobby) String() string {
	if i < 0 || i >= Hobby(len(_Hobby_index)-1) {
		return "Hobby(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Hobby_name[_Hobby_index[i]:_Hobby_index[i+1]]
}
